pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'step1'
            }
        }
        stage('Test') {
            steps {
                echo 'step2'
            }
        }
        stage('Deliver') {
            steps {
               echo 'step3'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
